apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  terminationGracePeriodSeconds: 30
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: europe-central2-docker.pkg.dev/nestjs-reservations/payments/production
          imagePullPolicy: "Always"
          name: payments
          env:
            - name: PORT
              value: '3001'
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3001
